Repository e2b-dev/code-interpreter, pull requests merged in 2025-05, with the labels that each got.

#97 Updated template with SWC compiler for TypeScript
  .changeset/dull-flies-bow.md
  template/.ts.swcrc
  template/Dockerfile
  template/test.Dockerfile
Labels: feature

#91 Added TypeScript support to the code interpreter
  .changeset/tiny-adults-breathe.md
  js/tests/defaultKernels.test.ts
  template/.ts.swcrc
  template/server/contexts.py
  template/server/messaging.py
Labels: feature

#99 Added TypeScript language tests
  js/tests/defaultKernels.test.ts
  python/tests/async/test_async_default_kernels.py
  python/tests/sync/test_default_kernels.py
Labels: improvement

#102 Configure code interpreter server idle timeout
  .changeset/stale-olives-cover.md
  template/start-up.sh
Labels: bug, improvement

#103 Update dependencies
  pnpm-lock.yaml
Labels: dependencies

#113 Adds tests for the updated JavaScript kernel
  js/tests/defaultKernels.test.ts
  python/tests/async/test_async_default_kernels.py
  python/tests/sync/test_default_kernels.py
Labels: improvement
