Repository e2b-dev/code-interpreter, pull requests merged in 2025-03, with the labels that each got.

#63 chore: update broken docs readme links for custom templating
  template/README.md
Labels: bug

#65 Fix SDK reference generation
  js/package.json
Labels: bug

#66 Update pnpm lockfile
  pnpm-lock.yaml
Labels: bug

#67 Send releases notification to dedicated channel
  .github/workflows/release.yml
Labels: improvement

#68 Fix `to_json` method for charts
  .changeset/smart-turkeys-study.md
  python/e2b_code_interpreter/models.py
  python/tests/charts/test_json.py
Labels: bug

#71 Update e2b sdk
  .changeset/rude-boats-live.md
  js/package.json
  pnpm-lock.yaml
  python/poetry.lock
  python/pyproject.toml
Labels: dependencies

#72 during sdk release check not just source code but dep files
  .github/scripts/is_release_for_package.sh
  .github/workflows/release.yml
Labels: improvement
