Repository e2b-dev/code-interpreter, pull requests merged in 2025-04, with the labels that each got.

#76 Show SDK ref dir only when it exists in GH release workflow
  .github/workflows/release.yml
Labels: bug

#75 Update Ubuntu base image to 22.04
  .github/workflows/charts_tests.yml
  .github/workflows/js_tests.yml
  .github/workflows/python_tests.yml
Labels: improvement

#79 Update esbuild to 0.25.0
  js/package.json
  pnpm-lock.yaml
Labels: dependencies

#84 bump beta dependencies
  js/package.json
  pnpm-lock.yaml
  python/pyproject.toml
Labels: python-rc, js-rc, dependencies

#85 re-generate python lock file
  python/poetry.lock
Labels: python-rc, dependencies

#87 Add support for proxy parameter
  .changeset/dull-bobcats-tie.md
  python/poetry.lock
  python/pyproject.toml
Labels: improvement

#89 Refactor workflows to run tests on PRs
  .github/workflows/charts_tests.yml
  .github/workflows/js_tests.yml
  .github/workflows/pull_request.yml
  .github/workflows/python_tests.yml
  .github/workflows/release.yml
Labels: improvement

#95 Security patches
  pnpm-lock.yaml
  python/poetry.lock
Labels: dependencies

#96 Update JS SDK target to es2017
  .changeset/salty-ideas-own.md
  js/tsup.config.js
Labels: improvement
